services:
  ros_dev:
    build: .
    image: ros2_humble_custom
    container_name: ros2_humble_container
    network_mode: host
    ipc: host
    privileged: true # Helpful for hardware communication with the xArm
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # NVIDIA variables (used by your PC, ignored by lab PC)
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Maps your local 'workspaces' folder to the container
      - ./workspaces:/ros2_ws/workspaces
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]